-- SQL script to create admin user 'tanay' in production database
-- Execute this in your production database via the Replit Database pane

-- First, let's create the hashed password
-- Note: You'll need to hash the password 'jump6bladder*dias0youse' using bcrypt with salt rounds 10

-- The hashed password for 'jump6bladder*dias0youse' would be generated by bcrypt
-- You can use the Node.js script below to generate it, or use an online bcrypt tool

-- Example INSERT statement (replace HASHED_PASSWORD_HERE with actual bcrypt hash):
INSERT INTO users (
  username, 
  email, 
  password, 
  first_name, 
  last_name, 
  is_admin,
  created_at,
  updated_at
) VALUES (
  'tanay',
  'tanay@admin.com',
  'HASHED_PASSWORD_HERE', -- Replace with actual bcrypt hash
  'Tanay',
  'Admin',
  true,
  NOW(),
  NOW()
) ON CONFLICT (username) DO UPDATE SET
  password = EXCLUDED.password,
  is_admin = EXCLUDED.is_admin,
  updated_at = NOW();

-- Alternative: If username conflict occurs with email instead:
-- You might need to use email as the conflict target instead:
-- ON CONFLICT (email) DO UPDATE SET ...